# Generated by Django 4.0.4 on 2022-06-28 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_myuploadfile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuploadfile',
            name='f_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
