# Generated by Django 4.0.4 on 2022-07-04 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_myuploadfile_f_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reference_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_fileName', models.CharField(default='', max_length=255)),
                ('reference_file', models.FileField(upload_to='')),
            ],
        ),
    ]
