# Generated by Django 4.0.4 on 2022-07-04 10:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0005_reference_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='myuploadfile',
            new_name='LO_Folder',
        ),
    ]
